### ISSUE TITLE
Category sorting by price is not working as expected

### ISSUE THREAD

**Issue by mishanino** [DivanteLtd/vue-storefront#1459]
The discount price doesn't effect to products order. Sorter uses the old price for the sorting by price.
https://demo.vuestorefront.io/c/men-11
![image](https://user-images.githubusercontent.com/4930295/43209680-ecc83ef2-9035-11e8-95dc-cbe548ee9bff.png)

**Comment by pkarw** [comment]
We should use the `final_price` instead of `price` for sorting because on the ES level price is not after discounts - it's original price

**Comment by mishanino** [comment]
@pkarw sorting by price still doesn't work, please, reopen the issue

**Comment by pkarw** [comment]
@mishanino do you have a final_price in the product entity? i

**Comment by mishanino** [comment]
@pkarw I updated local.json according to your commit and the latest version from master branch (1.2.0), on the https://demo.vuestorefront.io/ price sorting also doesn't work  
![image](https://user-images.githubusercontent.com/4930295/43633739-c8ac48ea-9712-11e8-9965-3052a4720528.png)

**Comment by mishanino** [comment]
@pkarw, could you explain what exactly do you need? it is not clear for me, by the way, you can check it yourself on the your demo site https://demo.vuestorefront.io/c/men-11

**Comment by vue-kacper** [comment]
@pkarw I'm investigating this now, it might be much more complex problem related with #1672 

There is also problem with proper ordering lazy loaded additional items. After changing sort order we should clear results first and then fetch fresh items.

For sure vue-strorefront-api returns wrong products orderind from ES

I'll do my best but it might not land in 1.3 till monday

**Comment by pkarw** [comment]
I believe this is not related to #1672 - please note that the products shown there are exactly the same (with the same price) - just differs by the variant.

The difference cames from Category.js:filterChanged - which is not applied server side. On the client side app - after applying filters is selecting the variant which regards the currently set color; if no color is set - then it's the first variant.

Server side - is not applying this logic. Therefore it's selecting the photo not from the first variant, by assigned to the product (product.thumb vs product.configurable_children[0].thumb).

I think it's not even an issue we should deal with right now (i mean #1672) as there are more important tasks.

This is my guess - I can be wrong. My first guess regarding this issue was that for filters there are prices without tax being used. But it doesn't seem like this with the given example

**Comment by vue-kacper** [comment]
@pkarw I figured it out - it's a mistake in sample input data, I'm not sure how many products are affected

![final_price](https://user-images.githubusercontent.com/42430550/44910691-76e5ce00-ad24-11e8-94c0-63726c5290b6.PNG)

For this product full price is incorrect in 

`vue-storefont-api/var/catalog.json`

**Comment by pkarw** [comment]
`var/catalog.json` is automatically generated from `demo-magento2.vuestorefront.io`; what's the price there?

It may be kind of difference on the settings -> `priceInclTax` is calculated on our side and `final_price` is imported directly from Magento; so it means that priceInclTax probably contains tax - and if Magento is set to display netto prices (not sure) final_price is Nett price and displayed price is a Gross price.

If this is a reason, then it works just fine (and can be fixed by magento settings)

**Comment by vue-kacper** [comment]
Prices in Magento and Vue Storefront for the same product behave differently:

`http://demo-magento2.vuestorefront.io/caesar-warm-up-pant.html`

`https://demo.vuestorefront.io/p/MP01/caesar-warm-up-pant-742/MP01`

Very interesting scenario is when you choose `size: 32` and `color: Gray` - there is big gap between price in M and VS. 

but for the Purple color of this product prices are the same in M and VS

**Comment by pkarw** [comment]
Fixed with the #1757

**Comment by mishanino** [comment]
@pkarw, sorting by price still doesn't work https://demo.vuestorefront.io/c/men-11
http://joxi.ru/E2pgGYvS7OLG5m

**Comment by EsteraVendic** [comment]
@pkarw Can you check again?

1. Go to https://demo.vuestorefront.io/c/men-11
2. Sort on price lowest
3. Check prices

Result:
![image](https://user-images.githubusercontent.com/30499229/47842313-9e0c5a80-ddbc-11e8-9d97-27b01edb5078.png)

**Comment by pkarw** [comment]
Ok, this needs to be checked on freshly imported database

**Comment by DrNik** [comment]
Hi _noob_ here and facing similar issue, the odd thing is that on dev env everything seems to work find but in prod env (with same data source, same Magento 2) I get the wrong behaviour.
What I can see is that the api call: /api/catalog/vue_storefront_catalog/product/_search?[...] responsible for sorting is returning 2 different payloads:

- on dev the sort property per each item in  the "hits" attribute is valued with the price of each item
```
"hits": {
    "total": 3,
    "max_score": null,
    "hits": [
      {
        "_index": "vue_storefront_catalog_1542353026",
        "_type": "product",
        "_id": "31",
        [...]
        },
        "sort": [
          119.99
        ]
      },
      {
        "_index": "vue_storefront_catalog_1542353026",
        "_type": "product",
        "_id": "49",
        [...]
        },
        "sort": [
          16.99
        ]
      },
      {
        "_index": "vue_storefront_catalog_1542353026",
        "_type": "product",
        "_id": "43",
        [...]
        },
        "sort": [
          13.99
        ]
      }
    ]
  }
```

- on prod environment the same search api call return "sort" valued "infinity"
```
"hits": {
    "total": 3,
    "max_score": null,
    "hits": [
      {
        "_index": "vue_storefront_catalog_1542356901",
        "_type": "product",
        "_id": "43",
        [...]
        },
        "sort": [
          "Infinity"
        ]
      },
      {
        "_index": "vue_storefront_catalog_1542356901",
        "_type": "product",
        "_id": "49",
        [...]
        },
        "sort": [
          "Infinity"
        ]
      },
      {
        "_index": "vue_storefront_catalog_1542356901",
        "_type": "product",
        "_id": "31",
        [...]
        },
        "sort": [
          "Infinity"
        ]
      }
    ]
  }
```
I checked config files but I see no differences that that could justify such a behavior.

Tested it on v1.5.0

Am I missing sometihng here?

Thanks

**Comment by DrNik** [comment]
Sorry ,my bad, I forgot to set PRODUCTS_SPECIAL_PRICES and PRODUCTS_RENDER_PRICES to **true** env variables for my mage2vs prod env.

_Noob question requires noob solution_
