### ISSUE TITLE
Clicking on a product in wishlist triggers the wrong product variation

### ISSUE THREAD

**Issue by Tjitse-E** [DivanteLtd/vue-storefront#1600]
### Steps to reproduce

1. Go to https://demo.vuestorefront.io/p/MSH10/sol-active-short-1007/MSH10-32-Blue
2. Add a few products to the wishlist
3. Select a different color. 
4. Go to the related product
5. Click on a product from the wishlist

### Expected result:
The correct product variant is showed, in this case the black shorts and the blue shorts.

### Actual result
The green and purple shorts are displayed, instead of the correct products in the wishlist.

![error_vs_related_favourites](https://user-images.githubusercontent.com/14849044/44258191-905c2580-a20e-11e8-9b22-d4909c837c62.gif)

**Comment by pkarw** [comment]
Thanks! We're adding the main product to the wishlist - it's kind of enhancement to pass the selected `childSku` with it

**Comment by vue-kacper** [comment]
@Tjitse-E I can't reproduce this issue, can you please check from your side and confirm that this issue is solved?

**Comment by Tjitse-E** [comment]
@vue-kacper No, I can still reproduce this issue in the demo store.

**Comment by pkarw** [comment]
This is because changing colors on the product page doesn't affect the page URL - so then after using the wishlist to navigate no valid data fetch is called (as the URL is exactly the same).
`  watch: {
    '$route.params.parentSku': 'validateRoute'
  },
`

We probably need to add kind of additional watcher to reload the product if it's needed
