### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by ladrua** [DivanteLtd/vue-storefront#1775]
I am trying to bring up the project with `docker-compose up` but getting this error:

```
vue_1       | yarn install v1.9.4
vue_1       | [1/5] Validating package.json...
vue_1       | [2/5] Resolving packages...
vue_1       | [3/5] Fetching packages...
vue_1       | info fsevents@1.2.4: The platform "linux" is incompatible with this module.
vue_1       | info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
vue_1       | [4/5] Linking dependencies...
vue_1       | warning " > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
vue_1       | [5/5] Building fresh packages...
vue_1       | success Saved lockfile.
vue_1       | Done in 9.89s.
vue_1       | yarn run v1.9.4
vue_1       | $ cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --mode production --progress --hide-modules
vue_1       | WARNING: NODE_ENV value of 'docker' did not match any deployment config file names.
vue_1       | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/de-DE.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/en-US.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/es-ES.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/fr-FR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/it-IT.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/jp-JP.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/nl-NL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pl-PL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pt-BR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/ru-RU.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/theme-default/resource/i18n/en-US.csv
vue_1       | Writing JSON file: de-DE.json
vue_1       | Writing JSON file: en-US.json
vue_1       | Writing JSON file: es-ES.json
vue_1       | Writing JSON file: fr-FR.json
vue_1       | Writing JSON file: it-IT.json
vue_1       | Writing JSON file: jp-JP.json
vue_1       | Writing JSON file: nl-NL.json
vue_1       | Writing JSON file: pl-PL.json
vue_1       | Writing JSON file: pt-BR.json
vue_1       | Writing JSON file: ru-RU.json
vue_1       | Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
vue_1       |  - configuration.module.rules[3].include should be one of these:
vue_1       |    RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? } | [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
vue_1       |    -> One or multiple rule conditions
vue_1       |    Details:
vue_1       |     * configuration.module.rules[3].include should be an instance of RegExp
vue_1       |     * configuration.module.rules[3].include should be a string.
vue_1       |     * configuration.module.rules[3].include should be an instance of function
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of RegExp
vue_1       |     * configuration.module.rules[3].include[0]: The provided value "@vue-storefront" is not an absolute path!
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of function
vue_1       |     * configuration.module.rules[3].include[0] should be an array:
vue_1       |       [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
vue_1       |     * configuration.module.rules[3].include[0] should be an object.
vue_1       |     * configuration.module.rules[3].include should be an object.
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of RegExp
vue_1       |     * configuration.module.rules[3].include[0]: The provided value "@vue-storefront" is not an absolute path!
vue_1       |     * configuration.module.rules[3].include[0] should be an instance of function
vue_1       |     * configuration.module.rules[3].include[0] should be an array:
vue_1       |       [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
vue_1       |     * configuration.module.rules[3].include[0] should be an object.
vue_1       | error Command failed with exit code 1.
vue_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
vue_1 exited with code 1
```

The only thing that I have changed is in the docker-compose.yml file, as I have other apps in the same project the vue-storefront is in a subdir, so I have updated the Volume mounts to reflect the new path:

```
vue:
      # image: divante/vue-storefront:latest
      build:
        context: ./vue-storefront
        dockerfile: docker/vue-storefront/Dockerfile
      env_file: ./vue-storefront/docker/vue-storefront/default.env
      environment:
        VS_ENV: dev
      volumes:
        - './vue-storefront/babelrc:/var/www/.babelrc'
        - './vue-storefront/config:/var/www/config'
        - './vue-storefront/core:/var/www/core'
        - './vue-storefront/ecosystem.json:/var/www/ecosystem.json'
        - './vue-storefront/.eslintignore:/var/www/.eslintignore'
        - './vue-storefront/.eslintrc.js:/var/www/.eslintrc.js'
        - './vue-storefront/lerna.json:/var/www/lerna.json'
        - './vue-storefront/package.json:/var/www/package.json'
        - './vue-storefront/src:/var/www/src'
        - './vue-storefront/var:/var/www/var'
        - './vue-storefront/tsconfig.json:/var/www/tsconfig.json'
        - './vue-storefront/shims.d.ts:/var/www/shims.d.ts'
      tmpfs:
        - /var/www/dist
      ports:
        - '3000:3000'
```

**Comment by ladrua** [comment]
Ok, so I changed line 111 in webpack.base.config.js from `'@vue-storefront',` to `'/var/www/node_modules/@vue-storefront',`

Now it get further, but new error:
```
vue_1       | ERROR in ./core/service-worker-registration.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
```

I guess I must have missed something obious here...

**Comment by janmyszkier** [comment]
No, this seems to be broken only on master, but seem to work fine back in `114737a40eca26bbe28e779e10462ebb3a09ef8b`. Seems like a bug, unintentional or not.

**Comment by pkarw** [comment]
OK guys, seems like problem with relative paths with webpack - fixed here:
https://github.com/DivanteLtd/vue-storefront/commit/093166377f29180633e4a3cc1fc78d2171e8cb6f

**Comment by ladrua** [comment]
Thank you @pkarw but thats what I tried, see my second comment, I still get that error with latest master build.

**Comment by pkarw** [comment]
I dont have any error after this change have you tried to run “yarn install” to create the symlinks for virtual @ folders?

**Comment by ladrua** [comment]
But thats run in the vue-storefront.sh script on startup? Do I need to run it again? Or are we talking outside the container?

**Comment by pkarw** [comment]
I had this problem outside the container - so if you’re using container it should work just fine. This is strange error you’re getting. @pszreder can you take a look at it?

**Comment by ladrua** [comment]
﻿﻿﻿﻿﻿﻿﻿﻿﻿This is the complete log:
```
vue_1       | yarn install v1.9.4
vue_1       | [1/5] Validating package.json...
vue_1       | [2/5] Resolving packages...
vue_1       | [3/5] Fetching packages...
vue_1       | info fsevents@1.2.4: The platform "linux" is incompatible with this module.
vue_1       | info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
vue_1       | [4/5] Linking dependencies...
vue_1       | warning " > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
vue_1       | [5/5] Building fresh packages...
vue_1       | success Saved lockfile.
vue_1       | Done in 11.13s.
vue_1       | yarn run v1.9.4
vue_1       | $ cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --mode production --progress --hide-modules
vue_1       | WARNING: NODE_ENV value of 'docker' did not match any deployment config file names.
vue_1       | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/de-DE.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/en-US.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/es-ES.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/fr-FR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/it-IT.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/jp-JP.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/nl-NL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pl-PL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pt-BR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/ru-RU.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/theme-default/resource/i18n/en-US.csv
vue_1       | Writing JSON file: de-DE.json
vue_1       | Writing JSON file: en-US.json
vue_1       | Writing JSON file: es-ES.json
vue_1       | Writing JSON file: fr-FR.json
vue_1       | Writing JSON file: it-IT.json
vue_1       | Writing JSON file: jp-JP.json
vue_1       | Writing JSON file: nl-NL.json
vue_1       | Writing JSON file: pl-PL.json
vue_1       | Writing JSON file: pt-BR.json
vue_1       | Writing JSON file: ru-RU.json
vue_1       |  68% building modules 964/997 modules 33 active ...e_modules/lodash/_isStrictComparable.jsDEPRECATION WARNING on line 7, column 8 of stdin:
vue_1       | Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
vue_1       | Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.
vue_1       |
Hash: 6ddbcd01277bfb468448
vue_1       | Version: webpack 4.20.2
vue_1       | Time: 45267ms
vue_1       | Built at: 2018-09-27 13:31:17
vue_1       |  24 assets
vue_1       | Entrypoint app = runtime.js runtime.js.map vendor.js vendor.js.map app.js app.js.map
vue_1       |
vue_1       | ERROR in ./core/service-worker-registration.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/client-entry.ts 11:0-59
vue_1       |
vue_1       | ERROR in ./core/plugins/event-bus/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/client-entry.ts 5:0-62 25:8-16 33:8-16 116:0-8 204:0-8 269:0-8 280:0-8
vue_1       |
vue_1       | ERROR in ./src/themes/default/plugins/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 36:0-24
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/extensions/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 19:0-50 57:29-49
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/themes/default/extensions/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 18:0-57 57:51-76
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./core/lib/extensions.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 11:0-69 57:4-22
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/themes/default/store/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 17:0-39 23:46-58
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./core/lib/themes.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 10:0-90 37:20-27 41:19-25 45:20-27 58:4-17
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./core/router/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 9:0-49 50:16-22 52:16-22 57:84-90 58:37-43 60:31-37
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/themes/default/App.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/default/App.vue?vue&type=script&lang=js&)
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./src/themes/default/App.vue?vue&type=script&lang=js& 1:0-169 1:185-188 1:190-356 1:190-356
vue_1       |  @ ./src/themes/default/App.vue
vue_1       |  @ ./core/app.ts
vue_1       |  @ ./core/client-entry.ts
vue_1       | Child html-webpack-plugin for "index.html":
vue_1       |      1 asset
vue_1       |     Entrypoint undefined = index.html
vue_1       | error Command failed with exit code 2.
vue_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pszreder** [comment]
@ladrua lucky guess - could you try to start "docker-compose up" with the "--build" arg?

**Comment by pkarw** [comment]
We've added as afix tsconfig.json to the container - hasn't been included there in 1.3.0 :( Could You prone Your storage and rebuild it to make sure the file is there? Coyuld You also paste Your tsconfig.json? In the develop and master branch for sure `files` section is not empty as the message sugests

**Comment by janmyszkier** [comment]
:thinking: I just cloned master from scratch few minutes before posting this. 
If the code is actually looking for `/tsconfig.json` (root dir file), the files contains reference to `shims`. Either way, that still fails to build. Maybe still wrong path reference somewhere?

**Comment by ladrua** [comment]
Hm I'm getting same error as you @janmyszkier when I run with these volume mounts:
```
        - './vue-storefront/babelrc:/var/www/.babelrc'
        - './vue-storefront/config:/var/www/config'
        - './vue-storefront/core:/var/www/core'
        - './vue-storefront/ecosystem.json:/var/www/ecosystem.json'
        - './vue-storefront/.eslintignore:/var/www/.eslintignore'
        - './vue-storefront/.eslintrc.js:/var/www/.eslintrc.js'
        - './vue-storefront/lerna.json:/var/www/lerna.json'
        - './vue-storefront/package.json:/var/www/package.json'
        - './vue-storefront/src:/var/www/src'
        - './vue-storefront/var:/var/www/var'
```

And if I add these two mounts: (I read somewhere in an issue that these were missing)
```
        - './vue-storefront/tsconfig.json:/var/www/tsconfig.json'
        - './vue-storefront/shims.d.ts:/var/www/shims.d.ts'
```
I get these errors again:
```
vue_1       | yarn install v1.9.4
vue_1       | [1/5] Validating package.json...
vue_1       | [2/5] Resolving packages...
vue_1       | [3/5] Fetching packages...
vue_1       | info fsevents@1.2.4: The platform "linux" is incompatible with this module.
vue_1       | info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
vue_1       | [4/5] Linking dependencies...
vue_1       | warning " > karma-webpack@3.0.5" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
vue_1       | [5/5] Building fresh packages...
vue_1       | success Saved lockfile.
vue_1       | Done in 12.35s.
vue_1       | yarn run v1.9.4
vue_1       | $ cross-env NODE_ENV=production webpack --config ./core/build/webpack.prod.client.config.js --mode production --progress --hide-modules
vue_1       | WARNING: NODE_ENV value of 'docker' did not match any deployment config file names.
vue_1       | WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/de-DE.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/en-US.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/es-ES.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/fr-FR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/it-IT.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/jp-JP.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/nl-NL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pl-PL.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/pt-BR.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/i18n/resource/i18n/ru-RU.csv
vue_1       | Processing translation file: /var/www/node_modules/@vue-storefront/theme-default/resource/i18n/en-US.csv
vue_1       | Writing JSON file: de-DE.json
vue_1       | Writing JSON file: en-US.json
vue_1       | Writing JSON file: es-ES.json
vue_1       | Writing JSON file: fr-FR.json
vue_1       | Writing JSON file: it-IT.json
vue_1       | Writing JSON file: jp-JP.json
vue_1       | Writing JSON file: nl-NL.json
vue_1       | Writing JSON file: pl-PL.json
vue_1       | Writing JSON file: pt-BR.json
vue_1       | Writing JSON file: ru-RU.json
vue_1       |  69% building modules 1021/1025 modules 4 active ...r/www/node_modules/lodash/_isKeyable.jsDEPRECATION WARNING on line 7, column 8 of stdin:
 69% building modules 1022/1025 modules 3 active ...r/www/node_modules/lodash/_isKeyable.jsIncluding .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
vue_1       | Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.
vue_1       |
Hash: 6ddbcd01277bfb468448
vue_1       | Version: webpack 4.20.2
vue_1       | Time: 51199ms
vue_1       | Built at: 2018-09-28 08:29:43
vue_1       |  24 assets
vue_1       | Entrypoint app = runtime.js runtime.js.map vendor.js vendor.js.map app.js app.js.map
vue_1       |
vue_1       | ERROR in ./core/service-worker-registration.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/client-entry.ts 11:0-59
vue_1       |
vue_1       | ERROR in ./core/plugins/event-bus/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/client-entry.ts 5:0-62 25:8-16 33:8-16 116:0-8 204:0-8 269:0-8 280:0-8
vue_1       |
vue_1       | ERROR in ./src/themes/default/plugins/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 36:0-24
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/extensions/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 19:0-50 57:29-49
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./core/lib/extensions.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 11:0-69 57:4-22
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./core/lib/themes.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 10:0-90 37:20-27 41:19-25 45:20-27 58:4-17
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/themes/default/extensions/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 18:0-57 57:51-76
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/themes/default/store/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 17:0-39 23:46-58
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./core/router/index.js
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./core/app.ts 9:0-49 50:16-22 52:16-22 57:84-90 58:37-43 60:31-37
vue_1       |  @ ./core/client-entry.ts
vue_1       |
vue_1       | ERROR in ./src/themes/default/App.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/themes/default/App.vue?vue&type=script&lang=js&)
vue_1       | Module build failed (from ./node_modules/babel-loader/lib/index.js):
vue_1       | Error: EISDIR: illegal operation on a directory, read
vue_1       |     at Object.fs.readSync (fs.js:675:18)
vue_1       |     at tryReadSync (fs.js:540:20)
vue_1       |     at Object.fs.readFileSync (fs.js:583:19)
vue_1       |     at ConfigChainBuilder.addConfig (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:146:32)
vue_1       |     at ConfigChainBuilder.findConfigs (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:96:16)
vue_1       |     at buildConfigChain (/var/www/node_modules/babel-core/lib/transformation/file/options/build-config-chain.js:61:13)
vue_1       |     at OptionManager.init (/var/www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:354:58)
vue_1       |     at File.initOptions (/var/www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
vue_1       |     at new File (/var/www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
vue_1       |     at Pipeline.transform (/var/www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
vue_1       |     at transpile (/var/www/node_modules/babel-loader/lib/index.js:50:20)
vue_1       |     at Object.module.exports (/var/www/node_modules/babel-loader/lib/index.js:173:20)
vue_1       |  @ ./src/themes/default/App.vue?vue&type=script&lang=js& 1:0-169 1:185-188 1:190-356 1:190-356
vue_1       |  @ ./src/themes/default/App.vue
vue_1       |  @ ./core/app.ts
vue_1       |  @ ./core/client-entry.ts
vue_1       | Child html-webpack-plugin for "index.html":
vue_1       |      1 asset
vue_1       |     Entrypoint undefined = index.html
vue_1       | error Command failed with exit code 2.
vue_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ladrua** [comment]
Ok, I got it working. I had an typo error in my first volume mount:
`- './vue-storefront/babelrc:/var/www/.babelrc'` should be `- './vue-storefront/.babelrc:/var/www/.babelrc'`

The error you have @janmyszkier I solved by adding these two files to mount in docker-compose:
```
        - './vue-storefront/tsconfig.json:/var/www/tsconfig.json'
        - './vue-storefront/shims.d.ts:/var/www/shims.d.ts'
```

**Comment by pkarw** [comment]
Awesome! Will You propose a PR please?

**Comment by ladrua** [comment]
There it is. Thanks for your help!

**Comment by pkarw** [comment]
Thanks! Please let me know guys if we can then close this issue

**Comment by ladrua** [comment]
Looks good to me! But as a sidenote, it's not a great idea to volume mount files directly, should be kept to dirs because some editors break the file mount into the docker container if files get edited(vi,vim,++). Not sure how to solve easily on this project, but I can have a look as I get into the project.
