### ISSUE TITLE
Lack of possbility to buy some specific products

### ISSUE THREAD

**Issue by ibugaj** [DivanteLtd/vue-storefront#2360]
## Current behavior
Some specific products can't be bought. There is notification: "_The order can not be transfered because of server error. Order has been queued_"
Error 500 in Console.

![image](https://user-images.githubusercontent.com/47220013/52219432-e7c57f00-289c-11e9-8ae5-182509e52e3e.png)

## Expected behavior
Possibility to buy available products

## Steps to reproduce the issue
1. Add to Cart product: **Yoga Adventure** SKU:240-LV06
2. Proceed with checkout
3. Click button "Place the order"

## Environment details
https://test.storefrontcloud.io/

## Additional information
I noticed, that problem appears when Checkout hasn't Shipping section

**Comment by pkarw** [comment]
Ok, so it’s just with virtual products, correct?

**Comment by ibugaj** [comment]
Yes, it looks like that

**Comment by ibugaj** [comment]
Sorry, I closed issue by mistake ;)

**Comment by pkarw** [comment]
Fixed with: https://github.com/DivanteLtd/vue-storefront-api/commit/d11a21a614632c00f8a375aed96123837787ded3

**Comment by pkarw** [comment]
Yes, but not yet deployed

**Comment by mimustafa** [comment]
We are still having problem when there is virtual product and there is no shipping address Here is Error: Error while adding shipping address at o2m.js:249:27
