### ISSUE TITLE
TypeError: Invalid apiVersion "5.5", expected a function or one of _default, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6.0, 5.6, 2.4, 1.7, 0.90, 6.7, 7.0, 7.x, master

### ISSUE THREAD

**Issue by yohanespradono** [DivanteLtd/vue-storefront#2413]
## Current behavior
While doing " Importing data from magento into ElasticSearch...", it was taking forever, then I canceled it.
I got this error on vue-storefront/var/log/install.log

```
== CREATING NEW DATABASE ==
/home/don/Web/showroom/vue-storefront-api/node_modules/elasticsearch/src/lib/utils.js:285
      throw new TypeError(err);
      ^

TypeError: Invalid apiVersion "5.5", expected a function or one of _default, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6.0, 5.6, 2.4, 1.7, 0.90, 6.7, 7.0, 7.x, master
    at Object.utils.funcEnum (/home/don/Web/showroom/vue-storefront-api/node_modules/elasticsearch/src/lib/utils.js:285:13)
    at new Client (/home/don/Web/showroom/vue-storefront-api/node_modules/elasticsearch/src/lib/client.js:70:33)
    at Object.<anonymous> (/home/don/Web/showroom/vue-storefront-api/migrations/.common.js:17:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

 == REVIEWS IMPORTER ==
2019-02-09T06:32:23.444Z - debug: Elasticsearch module initialized!

info: Winston logging library initialized.

2019-02-09T06:32:23.581Z - error: Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Invalid apiVersion "5.5", expected a function or one of _default, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6.0, 5.6, 2.4, 1.7, 0.90, 6.7, 7.0, 7.x, master
```

## Expected behavior
Importing run smooth

## Steps to reproduce the issue
yarn installer

## Repository
https://github.com/DivanteLtd/vue-storefront

# Can you handle fixing this bug by yourself?
No.

## Environment details
- OS: Deepin 15.9.1
- Node: v8.11.2

**Comment by pkarw** [comment]
Elastic 6.x is not yet supported. Please do use 5.x

**Comment by yohanespradono** [comment]
but mine is 5.6

```
➜  vue-storefront-api git:(master) docker-compose -f docker-compose.yml -f docker-compose.nodejs.yml up -d
Starting vue-storefront-api_redis_1 ... done
Starting elasticsearch              ... done
Starting vue-storefront-api_app_1    ... done
Starting vue-storefront-api_kibana_1 ... done
➜  vue-storefront-api git:(master) curl -XGET localhost:9200
{
  "name" : "cToNYak",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "ZLu8gsYRTAKukWrOBINeZw",
  "version" : {
    "number" : "5.6.11",
    "build_hash" : "bc3eef4",
    "build_date" : "2018-08-16T15:25:17.293Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}

```

**Comment by pkarw** [comment]
OK, that changes the perspective :) Please try do change:
https://github.com/DivanteLtd/vue-storefront-api/blob/9465bdbbc5d48ad480ae71e7ee0de9044f014d33/migrations/.common.js#L10

to '5.6' and if it works then You might want open a Pull Request with a fix

**Comment by pkarw** [comment]
@mdanilowicz

**Comment by lukeromanowicz** [comment]
We could consider moving that constant into config instead of hardcoding 5.6.

**Comment by pkarw** [comment]
@lukeromanowicz let's do it - please just check up with @mdanilowicz

**Comment by yohanespradono** [comment]
I found the issue.  In vue-storefront-api/package.json, it has "elasticsearch": "^15.2.0", and It fetch elasticsearch 15.4.1. and elasticsearch node module 15.4.1 doesn't support apiVersion 5.5.

**Comment by pkarw** [comment]
Thanks! Fixed with the https://github.com/DivanteLtd/vue-storefront-api/releases/tag/v1.8.1

**Comment by yohanespradono** [comment]
thx, but the error still occur. That's because the apiVersion in node_modules/mage2vuestorefront/src/adapters/nosql/elasticsearch.js is still 5.5

**Comment by pkarw** [comment]
OK, fixed with https://github.com/DivanteLtd/mage2vuestorefront/commit/9ff66feb861330d73b5eec207d19ea9e5df243db

**Comment by coatesjonathan** [comment]
Hi guys, I am still getting this issue, I can never seem to import the data.
And I get a slightly different error:

```
ERROR                                                                                                                         │
│                                                                                                                               │
│ Error: Can't import data into ElasticSearch.                                                                                  │
│     at Promise (/core/scripts/installer.js:327:16)                     │
│     at new Promise (<anonymous>)                                                                                              │
│     at Backend.importElasticSearch (/core/scripts/installer.js:323:12) │
│                                                                                                                               │
│ Please check log file for details: /var/log/install.log
```

**Comment by coatesjonathan** [comment]
Think I found the issue...
Redis default host for me is 127.0.0.1 not "localhost"
in /vue-storefront-api/config/local.json on line 35
