### ISSUE TITLE
With enabled useUrlDispatcher you get redirected to page-not-found directly after finding the product page

### ISSUE THREAD

**Issue by ResuBaka** [DivanteLtd/vue-storefront#2614]
## Current behavior
When going to product page with **useUrlDispatcher** set to true. Some times i get the page-not-found page. But when i open the page directly or in a new tab it is working. 

## Expected behavior
Going to the product page. 

## Steps to reproduce the issue
I have not found a 100% way. 
But for me i only need to click on product links in a category. There ruffly 1 out of 20 i have testet i get the problem. 
Then in the search i can get it to but with like a < 1% to get this issue.   

# Can you handle fixing this bug by yourself?
Yes

## Environment details
- Browser: Chromium 73
- OS: Arch Linux kernel 5.0.2
- Node: v10.15.3
- Code Version: v1.9.0-rc.1

## Additional information
I am searching for the problem and try to fix it. But in the ~20 minutes i searched why it is happening i only found out that the beforeEach in core/modules/url/router/beforeEach.ts is called two times. Which i was checking because for a splitt second i saw the product page but then the page-not-found page was shown to me. I will look deeper into it and will update this issue when i find something new to the problem.

**Comment by ResuBaka** [comment]
I have found that this is a problem with urlencoded url_path. There when you go to a product with an umlaut like "ÄÖÜ" it is working in the frontend but not the ssr. 
A second case is when the category you are in has an umlaut. Then when you go to the product he trys to go to the product page and trys to go to the category but the category url is now urldecoded but the url_path should be urlencoded. 

The whole problem could be an edgecase we have. I don't thing i can fix it in a short time, because i don't know where in the code base this problem really comes from. 
But with some help which code i should look into maybe i can fix it my self.

One thing that i could thing of as a fix is when checking for a url in url_path check for it with an urlencoded url and with the current url that gets searched.

**Comment by pkarw** [comment]
@ResuBaka could You provide us with the catalog.json database dump with the umlauts to let us test it and fix it? I would be very handful that we can re-use Your test data :)

**Comment by pkarw** [comment]
I believe we should add `urlEncode` in here: https://github.com/pkarw/vue-storefront/blob/a7950672775846c654b395c080272cd8c915bf5d/core/lib/multistore.ts#L131-L132 and then `urlDecode` in here: https://github.com/pkarw/vue-storefront/blob/a7950672775846c654b395c080272cd8c915bf5d/core/modules/url/router/beforeEach.ts#L13

**Comment by pkarw** [comment]
OK, I've come with a fix :)

**Comment by ResuBaka** [comment]
My problem with the latest Develop branch is still there. When i got time to look more into it i can give more info what it can be.

**Comment by pkarw** [comment]
@ResuBaka I've merged the changes to release/1.9 not sure if they've been merged to develop as well

**Comment by ResuBaka** [comment]
When you mean [this fix](https://github.com/pkarw/vue-storefront/commit/da58b6c59daa76b75a501aaddefcee21c6a3063d)? 
Then i have this locally, but i still have the problem.
