### ISSUE TITLE
Incorrect working of checkboxes in checkout

### ISSUE THREAD

**Issue by GabiDivante** [DivanteLtd/vue-storefront#2730]
## Current behavior

After marking the "ship to my default address" or "copy address data from shipping" checkbox, the form is not filled in with data, whereas after unmarking checkboxes - forms are filled in.
![incorrectoperationofcheckboxe](https://user-images.githubusercontent.com/49188852/56117548-9aceea80-5f68-11e9-9639-aa3e85edad2f.gif)

## Expected behavior
After selecting the "ship to my default address" or "copy address data from shipping" checkbox, the appropriate form is filled with data.

## Steps to reproduce the issue

1. Go to https://test.storefrontcloud.io
2. Add any product to the cart
3. Go to checkout
4. Login to your account (which has memorized shipping details)
5. Continue to shipping
6. Mark checkbox "ship to my default address" 
7. Unmark checkbox "ship to my default address" 
8. Continue to payment
9. Mark chceckbox "copy address data from shipping"
10. Unmark checkbox "copy address data from shipping"

## Can you handle fixing this bug by yourself?
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 73
- OS: Windows 10

## Additional information

This problem only appears on the environment https://test.storefrontcloud.io, does not appear on next and demo.

**Comment by pkarw** [comment]
@GabiDivante and @lukeromanowicz  I still have this issue with the second checkobx "Ship to my default address"

<img width="499" alt="Screenshot 2019-04-27 19 16 55" src="https://user-images.githubusercontent.com/211899/56852902-29f0e080-6921-11e9-929b-400623b38b4d.png">


Please do re-check it and re-check all the checboxes in the app as it seems like a global issue with this component
This issue doesn't apply to 1.9.0

**Comment by GabiDivante** [comment]
@pkarw @lukeromanowicz previously, I checked it on the branch and it was ok, now I checked it on develop
1. "Shipping to my default address" does not work correctly.

I also checked all other checkboxes, the problem with the action appears for:

2. My account -> My newsletter - after selecting the checkbox and saving the changes, then switching to another subpage and returning - the changes are not saved.
3.  Payment section in checkout (for logged in user with filled company data in My Profile) - the second checkbox appears "Use my billing data" - switching between checkboxes and selecting "I want to generate an invoice" do not work properly.

![Peek 2019-04-29 10-39](https://user-images.githubusercontent.com/49188852/56885715-66c9ee00-6a6d-11e9-8c52-503e9a1182b4.gif)

**Comment by pkarw** [comment]
Hi @dimasch how about this issue? :)

**Comment by dimasch** [comment]
@pkarw  In progress just now. ;)

**Comment by dimasch** [comment]
@pkarw Done.

**Comment by pkarw** [comment]
Thanks Dima

**Comment by alinadivante** [comment]
@dimasch we need to improve this, because now, if I mark "Copy address data from shipping" it is correctly filled, but if i change my mind and I want to choose "Use my billing data", then form is cleared. I have to unmark selected checkbox and mark it again.

![payment](https://user-images.githubusercontent.com/36628922/58414342-60825e00-807b-11e9-8593-0fadb3f85a7c.gif)

**Comment by patzick** [comment]
I've merged this now, so it will be available for tests:)

**Comment by alinadivante** [comment]
@dimasch @patzick unfortunately switching between above options (copy address data from shipping and use my billing data) still doesn't work correctly (form is cleared or address is not changed)

**Comment by dimasch** [comment]
@alinadivante Thanks. I will go to fix.

**Comment by pkarw** [comment]
@dimasch how about the status? :)

**Comment by dimasch** [comment]
@pkarw In progress. Actualize develop branch and today i will fix it.

**Comment by dimasch** [comment]
@pkarw I remember about the release 1.10rc1, and I will try to fix it over the weekend. ;)

**Comment by dimasch** [comment]
Ready. @pkarw 
I attached the video how it works after the fix.

**Comment by alinadivante** [comment]
@dimasch  I found one bug on your branch. Please see my video (it is about validation of Company name field)
![invoice](https://user-images.githubusercontent.com/36628922/59179447-51fb7280-8b62-11e9-9183-070a645a8be4.gif)

**Comment by dimasch** [comment]
Ok, thanks, i will fix today evening.

**Comment by dimasch** [comment]
@alinadivante Fixed. Pls, try to check.

**Comment by alinadivante** [comment]
@dimasch yeah, now it works :)
