### ISSUE TITLE
Problem with footer pages for non-default stores.

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront#3579]
## Current behavior
Links from footer (in non-default stores) redirect to pages without content, and CMS pages to 404 page not found.
When I open CMS page from the footer,  the following error occurs in dev console:
![image](https://user-images.githubusercontent.com/36628922/65161174-67244f00-da37-11e9-884a-4c0a2caf719c.png)
And if I open CMS via URL,  the following error occurs in dev console:
![image](https://user-images.githubusercontent.com/36628922/65161243-828f5a00-da37-11e9-8ea7-61a09d6a4890.png)

## Expected behavior
All links should work properly, without errors in dev console.

## Steps to reproduce the issue
1. Run the latest develop version with mulistore 
2. Go to /de or /it store
3. Check links from footer
4. Open CMS pages from footer
5. Open CMS via link, e.g http://localhost:3000/de/i/about-us

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by pkarw** [comment]
Seemingly these cms pages were not synced for lang. versions; which is fine and we should probably just better handle the 404 error (not having hydration/console errors); then to remove the links from footer if the `currentStoreView().storeCode !== config.i18n.defaultStorecode`

**Comment by andrzejewsky** [comment]
@alinadivante works for me, can you check again with the newest develop (maybe It has been fixed)?

**Comment by alinadivante** [comment]
@andrzejewsky I still have the same errors, so maybe I'll send you my config and then check again if the problem is also reproducible for you
