### ISSUE TITLE
Error: Cannot find module '/var/www/start' in Docker - Windows 10 / Windows Server

### ISSUE THREAD

**Issue by AntoniErdeg** [DivanteLtd/vue-storefront#4454]
## Current behaviour

When booting the vue-storefront-app service using docker on Windows 10 Professional Edition. The PM2 service will result in an error if you configure the NODE_ENV from "dev" to "production" (further explanation can be found below in the  Additional Information section) which will result in the following error across all PM2 instances:  "Error: Cannot find module '/var/www/start'"

After it phases through the docker configuration and setup via docker. These are the logs:

**PM2 boots the 4 instances successfully, but then soon after encounters, an error: "Error: Cannot find module '/var/www/start'". View logs for more information**
──────────┬────┬─────────┬─────┬────────┬─────────┬────────┬──────┬───────────┬──────┬──────────┐

│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ user │ watching │

├──────────┼────┼─────────┼─────┼────────┼─────────┼────────┼──────┼───────────┼──────┼──────────┤

│ server │ 0 │ cluster │ 247 │ online │ 0 │ 0s │ 131% │ 74.7 MB │ root │ disabled │

│ server │ 1 │ cluster │ 254 │ online │ 0 │ 0s │ 100% │ 62.7 MB │ root │ disabled │

│ server │ 2 │ cluster │ 265 │ online │ 0 │ 0s │ 104% │ 37.1 MB │ root │ disabled │

│ server │ 3 │ cluster │ 276 │ online │ 0 │ 0s │ 93% │ 30.9 MB │ root │ disabled │

└──────────┴────┴─────────┴─────┴────────┴─────────┴────────┴──────┴───────────┴──────┴──────────┘

[2020-05-24 04:24:58] PM2 log: Use `pm2 show <id|name>` to get more details about an app

[2020-05-24 04:24:58] PM2 log: [--no-daemon] Continue to stream logs

[2020-05-24 04:24:58] PM2 log: [--no-daemon] Exit on target PM2 exit pid=236

04:24:58 0|server | Error: Cannot find module '/var/www/start'

04:24:58 0|server | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

04:24:58 0|server | at Function.Module._load (internal/modules/cjs/loader.js:562:25)

04:24:58 0|server | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

04:24:58 0|server | at main (/var/www/node_modules/ts-node/src/bin.ts:226:14)

04:24:58 0|server | at Object.<anonymous> (/var/www/node_modules/ts-node/src/bin.ts:485:3)

04:24:58 0|server | at Module._compile (internal/modules/cjs/loader.js:778:30)

04:24:58 0|server | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

04:24:58 0|server | at Module.load (internal/modules/cjs/loader.js:653:32)

04:24:58 0|server | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

04:24:58 0|server | at Function.Module._load (internal/modules/cjs/loader.js:585:3)

04:24:58 1|server | Error: Cannot find module '/var/www/start'

04:24:58 1|server | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

04:24:58 1|server | at Function.Module._load (internal/modules/cjs/loader.js:562:25)

04:24:58 1|server | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

04:24:58 1|server | at main (/var/www/node_modules/ts-node/src/bin.ts:226:14)

04:24:58 1|server | at Object.<anonymous> (/var/www/node_modules/ts-node/src/bin.ts:485:3)

04:24:58 1|server | at Module._compile (internal/modules/cjs/loader.js:778:30)

04:24:58 1|server | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

04:24:58 1|server | at Module.load (internal/modules/cjs/loader.js:653:32)

04:24:58 1|server | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

04:24:58 1|server | at Function.Module._load (internal/modules/cjs/loader.js:585:3)

04:24:59 2|server | Error: Cannot find module '/var/www/start'

04:24:59 2|server | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

04:24:59 2|server | at Function.Module._load (internal/modules/cjs/loader.js:562:25)

04:24:59 2|server | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

04:24:59 2|server | at main (/var/www/node_modules/ts-node/src/bin.ts:226:14)

04:24:59 2|server | at Object.<anonymous> (/var/www/node_modules/ts-node/src/bin.ts:485:3)

04:24:59 2|server | at Module._compile (internal/modules/cjs/loader.js:778:30)

04:24:59 2|server | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

04:24:59 2|server | at Module.load (internal/modules/cjs/loader.js:653:32)

04:24:59 2|server | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

04:24:59 2|server | at Function.Module._load (internal/modules/cjs/loader.js:585:3)

04:24:59 3|server | Error: Cannot find module '/var/www/start'

04:24:59 3|server | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)

04:24:59 3|server | at Function.Module._load (internal/modules/cjs/loader.js:562:25)

04:24:59 3|server | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

04:24:59 3|server | at main (/var/www/node_modules/ts-node/src/bin.ts:226:14)

04:24:59 3|server | at Object.<anonymous> (/var/www/node_modules/ts-node/src/bin.ts:485:3)

04:24:59 3|server | at Module._compile (internal/modules/cjs/loader.js:778:30)

04:24:59 3|server | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

04:24:59 3|server | at Module.load (internal/modules/cjs/loader.js:653:32)

04:24:59 3|server | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

04:24:59 3|server | at Function.Module._load (internal/modules/cjs/loader.js:585:3)

## Expected behaviour

The service should boot and users should be able to connect to localhost:3000 or 0.0.0.0:3000 to see the vue-frontend.

## Steps to reproduce the issue

- By default the Repository has been configured so that the vue-frontend runs in DEV mode, therefore if you need to replace the key word: "dev" to "production" in the docker file and the docker-compose files - can then execute "docker-compose up -d" to build the docker image.

- Currently: this hasn't been configured to run on a windows platform (including my windows 2019 servers).

## Can you handle fixing this bug by yourself?

- [ X ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ X ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create a branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Not applicable as server doesn't even run
- OS:  Windows 10 Professional Edition - Version 1909 (OS Build 1836.836)
- Node: v12.16.3 
- Code Version:  Latest: https://github.com/DivanteLtd/vue-storefront/tree/6cd57ab269a8a31ed8eb5a18ebc8934abe1b9b55 

## Additional information

- The current version of vue-frontend works perfectly fine if you don't change the NODE_ENV settings from "dev" to "production" in the docker file and the docker-compose files. The repository itself defaults back to "yarn dev" due to the shell file (vue-frontend.sh) when you execute "yarn start" / "npm start".  

- By default when directly downloaded from the repository https://github.com/DivanteLtd/vue-storefront - "yarn start" is the equivalent of "yarn dev" .

- As vue-storefront caches the vue-storefront interface. When testing this issue please use a fresh incognito mode page. (Don't be tricked by the cached version from the previous dev build).

**Comment by janimaljanen** [comment]
Had the same issue, resolved by fixing ecosystem.json as mentioned in:
https://github.com/DivanteLtd/vue-storefront/issues/4191#issuecomment-602535658

**Comment by cewald** [comment]
I've had the same error if I run it from another directory – or in our case: using `supervisord` + `--no-daemon` (because our hoster needs to). I'm using `pm2` v2.10.4 and `yarn` v1.22.4.

This is the `ecosystem.json` that finally worked:
```json
{
  "apps": [
    {
      "name": "server",
      "max_memory_restart": "2G",
      "instances": "6",
      "exec_mode": "cluster",
      "env": {
        "TS_NODE_PROJECT": "tsconfig-build.json",
        "NODE_ENV": "production"
      },
      "interpreter": "./node_modules/.bin/ts-node",
      "script": "./core/scripts/server.ts",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "ignore_watch": [
        "core/build/config.json",
        "node_modules"
      ]
    }
  ]
}
```

**Comment by AntoniErdeg** [comment]
> [#4191 (comment)](https://github.com/DivanteLtd/vue-storefront/issues/4191#issuecomment-602535658)

The ecosystem.json configuration solution linked above **doesn't resolve the issue**. If you try the configuration and build the docker service:  Yes, the PM2 servers and docker build does boot successfully, but the servers will build and rebuild the service indefinitely - If you look into the service logs. **When testing your solution: Please test use a fresh incognito mode page or form of private browsing that doesn't save cached data from previous builds.** 

Both comments I have received aren't a successful solution to make the service run successfully and stably. Additionally, I did try the provided attempt at a solution before posting this bug report, but as it wasn't fixed for over 2 months - I thought I would highlight the preexisting issues and try to provide an in-depth summary into the issue.

Sorry for the late update: I have been a bit busy lately and I thought I would retry the provided solution with a fresh install and clean windows system. There was no change.

Additionally, I have customised my system to boot and configure all required services for the system to run successfully simultaneously and using a single command. 

`Creating mysql_service      ... done
Creating elasticsearch      ... done
Creating redis              ... done
Creating vue-storefront-app     ... done
Creating phpmyadmin_service ... done
Creating apache2_service        ... done
Creating vue-storefront-api-app ... done
Creating kibana                 ... done
`  

The only problematic service is the front-end service. I have tested my solution with the vue-storefront frontend configured as 'dev' with no issues. Other services are configured for production modes with no issues.

@JCown @mdanilowicz @gibkigonzo @cewald

**Comment by boichoi** [comment]
Dear r u installed on vue-storefront-api on windows 10?

**Comment by boichoi** [comment]
kindly guide i could not do that...

**Comment by AntoniErdeg** [comment]
@boichoi I’m going to assume you probably lack the ability to understand the code properly without the assistance of StackOverflow or similar platform. If you’re use the code directly from the GITHub repository - it will boot into ‘Dev’. 

Yes, it will boot properly using ‘dev’.

The problem is: ‘Production’ mode with it boots on pm2 services with 6 instances. The service can’t boot. I’m assuming it is due to the config file or the server.js file (maybe even both). I haven’t spent anymore time trying to troubleshoot the issue since reporting this issue.

I’m not at my computer right now and I will be a couple of hours before I’m on it again.

I might as well upload a YouTube video guide to the issue to help people actually understand what is happening. The first part will include the default repositories and services. The second half: I will make the changes to make it boot into ‘production’ according to how the code is setup. Additionally, you might be able to see how I actually configured my docker file to boot, install and run all services using a single command.

**Comment by AntoniErdeg** [comment]
@gibkigonzo @pkarw I have done some further testing on this issue. When testing my project on IOS and Linux - There is no problem with the booting or running of this service  on those platforms. When the project was tested on the windows platform - It won't boot?? Using the exact same commands, the exact same project and package file. All systems are using yarn and have the exact same version of yarn installed - It just simply doesn't want to boot on windows without resulting in an error . 

It is a very strange issues that I have spent the past week trying to resolve this issue and i have tested this issue on multiple machines. I guess not many users use windows servers or the windows platform when using your open source project.

This issues is related to this:  #4454 

@cewald @mdanilowicz @janimaljanen

**Comment by AntoniErdeg** [comment]
> @gibkigonzo @pkarw I have done some further testing on this issue. When testing my project on IOS and Linux - There is no problem with the booting or running of this service on those platforms. When the project was tested on the windows platform - It won't boot?? Using the exact same commands, the exact same project and package file. All systems are using yarn and have the exact same version of yarn installed - It just simply doesn't want to boot on windows without resulting in an error .
> 
> It is a very strange issues that I have spent the past week trying to resolve this issue and i have tested this issue on multiple machines. I guess not many users use windows servers or the windows platform when using your open source project.
> 
> This issues is related to this: #4454
> 
> @cewald @mdanilowicz @janimaljanen


Argh, I discovered the issue. As I prefer the Linux CMD interface: I use GitBash and even when you're an administrator, you will still need to launch gitBash as administrator and then boot the service.

**Comment by dhouhamaa** [comment]
I have the same issue but in kubernetes pods . The cmd "yarn start"  works fine in linux machine and macOs but not inside the pods , showing this error "Error: Cannot find module '/var/www/start'" . Any idea how to fix it please ?

**Comment by AntoniErdeg** [comment]
> I have the same issue but in kubernetes pods . The cmd "yarn start" works fine in linux machine and macOs but not inside the pods , showing this error "Error: Cannot find module '/var/www/start'" . Any idea how to fix it please ?

Have you made sure to run “yarn build” before running “yarn start”. Yarn start requires the build files that are created in var/www/.

It is an honest mistake, but I’m pretty sure that is your issue
