### ISSUE TITLE
Copy address data from shipping - box doesn't select

### ISSUE THREAD

**Issue by nsuberi** [DivanteLtd/vue-storefront#754]
https://demo.vuestorefront.io/checkout

On step 3 when I try to click the box to "copy address data from shipping" it checks and then automatically unchecks without copying over the information.

~ Nathan

**Comment by nsuberi** [comment]
Same type of behavior happens when trying to click "I want to generate an invoice for the company"

**Comment by pkarw** [comment]
Thanks! Please advise us on which device this behavior occurs? You’ve tested it on demo or on the latest version from the Github? You’re making the order as a guest or logged in user?

I’ve tested it as guest on iPhone and seems to work just fine

![537c428f-2416-4e69-9c8d-40d68c6062c2](https://user-images.githubusercontent.com/211899/36643492-685921cc-1a4c-11e8-8192-e4a93e418b1a.png)
![04ff5d76-b03e-4fbb-8ebb-434d33184908](https://user-images.githubusercontent.com/211899/36643493-68798fca-1a4c-11e8-85c4-3991ac610fbf.png)

**Comment by nsuberi** [comment]
Hi P,

I tested from the demo site on Safari as a guest.

I'm following along w/ your progress through watching the GitHub and am excited for y'alls launch March 1. I hope to be one of your beta testers! My parents run a mom-and-pop shoe and jewelry shop in Annapolis, MD, and I am going to try to integrate your front-end with Magento to create an e-commerce site with them.

~ Nathan

**Comment by pkarw** [comment]
Yeah, that sounds great! The issue: t's strange, it's working for me just fine on iOS Safari :( @akbarik when you'll finish 1.0RC tasks you can take a look at it :)

**Comment by akbarik** [comment]
Hi @nsuberi! Can you also check if that buggy behavior appears on test.vuestorefront.io too?

**Comment by akbarik** [comment]
I could reproduce this bug on Safari. Something's wrong with the button itself. But if you press on a text beside the button, it works. I'll try to fix it shortly.

**Comment by nsuberi** [comment]
Hi all, what are the credentials fro test.vuestorefront.io? They don't seem to be posted on the readme. Congratulations on 1.0RC!

**Comment by pkarw** [comment]
demo/!@#demo :) THanks!

**Comment by akbarik** [comment]
Hi @nsuberi! I think I fixed the issue. Can you please check it?

**Comment by akbarik** [comment]
I'm closing this issue, but if it's still not fixed, we'll open it again.

**Comment by nsuberi** [comment]
Hi all, apologies for slow response! I am still getting the same issue with test.vuestorefront.io on Safari 11.0.3 (13604.5.6). I made an account and logged in and it still occurred. I reloaded the page while logged in and it still occurred.

**Comment by pkarw** [comment]
@nsuberi demo and test are not yet updated after this fix :) Please test it locally or please do wait for the updates
