### ISSUE TITLE
Broken inheritance mechanism for logo.svg

### ISSUE THREAD

**Issue by jinn-magedev** [DivanteLtd/vue-storefront#920]
If you put your custom logo.svg to src/themes/your-theme/assets folder vue-storefront still returns image from core/assets/folder, but if your change file name from "logo.svg" to "logo1.svg" and update logo component to use logo1.svg it returns image from src/themes/your-theme/assets. Looks like file from core/assets has more priority than file from theme/assets. In my opinion it is a wrong approach, theme assets/files should have more priority than core/assets files

## Steps to reproduce
1. Create your custom theme
2. Put your custom logo.svg to assets folder in your theme

## Expected result
The logo image should be updated, app uses image from your theme/assets folder

## Actual result
The logo file is not changes, app uses image from core/assets folder

**Comment by pkarw** [comment]
@jinn-magedev thanks for this report; I belive it can be related to service worker caching strategy we had in place (cacheFirst) - https://github.com/DivanteLtd/vue-storefront/pull/924 -> I've fixed it

Please do the full rebuild to generate new Service Worker ('npm run build') and just after this step run npm dev

Of course, please do Clear Storage before the tests

**Comment by jinn-magedev** [comment]
@pkarw I pulled latest changes from master branch, ran 'npm run build' then "npm run dev", cleared storage but I still have this issue

**Comment by filrak** [comment]
https://github.com/DivanteLtd/vue-storefront/blob/master/core/scripts/server.js#L48 from what i see it should work. I'll test tomorrow... but tbh i think we should get rid of this inheritance mechanism and make alla ssets theme-specific. Now it's a bit confusing and radundant to have assets in core
